### ISSUE TITLE
Why 1 fields inserted as zero?

### ISSUE THREAD

**Issue by darkvovich** [oscarotero/simple-crud#47]
```
$tplArr = [
'automation_id' => (string) "yellow_m_1",
'type'          => $type,
'start_trigger' => $start_trigger,
'start_time'    => $start_time,
'message'       => $message,
'created' => date('Y-m-d H:i:s'),
'edited'  => date('Y-m-d H:i:s')
];
$newTask = $db->templates->create($tplArr);
$createTpl = $newTask->save();
```
All fields saved correctly, but automation_id always inserted as 0 (zero), WHY?

![image](https://user-images.githubusercontent.com/800438/143785688-7337e742-942e-4084-b459-d7c215c5f6d3.png)

![image](https://user-images.githubusercontent.com/800438/143785700-23a90953-ca50-429a-9506-3dd3bc6794af.png)

**Comment by oscarotero** [comment]
This is because all fields named `id` or ending with `_id` are interpreted as integers, [as you can see here](https://github.com/oscarotero/simple-crud/blob/master/src/Fields/Integer.php#L13). This is to make sure that all primary fields and foreign keys are integers. The only solution is to change the name of this field to something else (for example: `automation`, `automation_key`, etc)
